<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PdsTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pds_type')->insert([
            ['TransNo' => 50, 'TransGroup' => 200, 'ItemDesc' => 'Berambut gondrong', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur tertulis oleh PDS dicatat dalam buku pelanggaran ditanda tangani siswa dan diketahui orang tua.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:17:53.000', 'Group' => 'Sedang', 'Article' => 10],
            ['TransNo' => 60, 'TransGroup' => 200, 'ItemDesc' => 'Mengecat rambut dengan warna menyolok yang tidak p', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur tertulis oleh PDS dicatat dalam buku pelanggaran ditanda tangani siswa dan diketahui orang tua.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:17:57.000', 'Group' => 'Sedang', 'Article' => 11],
            ['TransNo' => 70, 'TransGroup' => 200, 'ItemDesc' => 'Nongkrong di luar lingkungan sekolah', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Arial;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:22:24.000', 'Group' => 'Berat', 'Article' => 14],
            ['TransNo' => 100, 'TransGroup' => 200, 'ItemDesc' => 'Memalsukan tanda tangan', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Arial;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:22:29.000', 'Group' => 'Berat', 'Article' => 15],
            ['TransNo' => 110, 'TransGroup' => 200, 'ItemDesc' => 'Mengedarkan berita bohong baik secara langsung ata', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Arial;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:22:43.000', 'Group' => 'Berat', 'Article' => 16],
            ['TransNo' => 120, 'TransGroup' => 200, 'ItemDesc' => 'Terlambat masuk sekolah', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur dan diingatkan dengan lisan oleh Penegak Disiplin Sekolah (PDS) dicatat dalam buku pelanggaran dan ditanda tangani siswa.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:10:30.000', 'Group' => 'Ringan', 'Article' => 1],
            ['TransNo' => 130, 'TransGroup' => 200, 'ItemDesc' => 'Memakai aksesoris yang tidak perlu dan tidak layak', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur dan diingatkan dengan lisan oleh Penegak Disiplin Sekolah (PDS) dicatat dalam buku pelanggaran dan ditanda tangani siswa.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:14:31.000', 'Group' => 'Ringan', 'Article' => 8],
            ['TransNo' => 190, 'TransGroup' => 200, 'ItemDesc' => 'Tidak masuk sekolah 4 (empat) sampai 6 (enam) tanp', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur tertulis oleh PDS dicatat dalam buku pelanggaran ditanda tangani siswa dan diketahui orang tua.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:15:18.000', 'Group' => 'Sedang', 'Article' => 1],
            ['TransNo' => 210, 'TransGroup' => 200, 'ItemDesc' => 'Mencemarkan nama baik pimpinan sekolah, guru atau ', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:20:59.000', 'Group' => 'Berat', 'Article' => 3],
            ['TransNo' => 220, 'TransGroup' => 200, 'ItemDesc' => 'Tidak memakai sepatu seragam sekolah', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur tertulis oleh PDS dicatat dalam buku pelanggaran ditanda tangani siswa dan diketahui orang tua.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:15:57.000', 'Group' => 'Sedang', 'Article' => 3],
            ['TransNo' => 250, 'TransGroup' => 200, 'ItemDesc' => 'Mencorat-coret fasilitas, inventaris atau lingkung', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur tertulis oleh PDS dicatat dalam buku pelanggaran ditanda tangani siswa dan diketahui orang tua.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:18:01.000', 'Group' => 'Sedang', 'Article' => 12],
            ['TransNo' => 270, 'TransGroup' => 200, 'ItemDesc' => 'Merusak barang atau fasilitas milik sekolah atau m', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur tertulis oleh PDS dicatat dalam buku pelanggaran ditanda tangani siswa dan diketahui orang tua.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:18:09.000', 'Group' => 'Sedang', 'Article' => 14],
            ['TransNo' => 290, 'TransGroup' => 200, 'ItemDesc' => 'Tidak masuk sekolah 10 (sepuluh) hari tanpa alasan', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:20:52.000', 'Group' => 'Berat', 'Article' => 1],
            ['TransNo' => 300, 'TransGroup' => 200, 'ItemDesc' => 'Tidak memakai jaket almamater sesuai hari-hari yan', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur tertulis oleh PDS dicatat dalam buku pelanggaran ditanda tangani siswa dan diketahui orang tua.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:16:19.000', 'Group' => 'Sedang', 'Article' => 4],
            ['TransNo' => 330, 'TransGroup' => 200, 'ItemDesc' => 'Membuang sampah sembarangan', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur tertulis oleh PDS dicatat dalam buku pelanggaran ditanda tangani siswa dan diketahui orang tua.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:17:32.000', 'Group' => 'Sedang', 'Article' => 5],
            ['TransNo' => 340, 'TransGroup' => 200, 'ItemDesc' => 'Melakukan seks bebas', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Arial;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:24:16.000', 'Group' => 'Berat', 'Article' => 18],
            ['TransNo' => 350, 'TransGroup' => 200, 'ItemDesc' => 'Terbukti membawa, menggunakan atau mengedarkan nar', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Dikeluarkan dari SMA Plus PGRI Cibinong tanpa ada sanksi atau peringatan sebelumnya.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:26:55.000', 'Group' => 'Luar Biasa', 'Article' => 2],
            ['TransNo' => 360, 'TransGroup' => 200, 'ItemDesc' => 'Pakai seragam dengan atribut yang tidak lengkap', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur dan diingatkan dengan lisan oleh Penegak Disiplin Sekolah (PDS) dicatat dalam buku pelanggaran dan ditanda tangani siswa.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:13:06.000', 'Group' => 'Ringan', 'Article' => 4],
            ['TransNo' => 370, 'TransGroup' => 200, 'ItemDesc' => 'Terbukti terlibat tawuran dengan sekolah lain atau', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Dikeluarkan dari SMA Plus PGRI Cibinong tanpa ada sanksi atau peringatan sebelumnya.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:27:16.000', 'Group' => 'Luar Biasa', 'Article' => 3],
            ['TransNo' => 390, 'TransGroup' => 200, 'ItemDesc' => 'Pakai sepatu secara tidak benar', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur dan diingatkan dengan lisan oleh Penegak Disiplin Sekolah (PDS) dicatat dalam buku pelanggaran dan ditanda tangani siswa.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:13:22.000', 'Group' => 'Ringan', 'Article' => 5],
            ['TransNo' => 400, 'TransGroup' => 200, 'ItemDesc' => 'Melakukan pinjaman on line', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Arial;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:24:21.000', 'Group' => 'Berat', 'Article' => 19],
            ['TransNo' => 410, 'TransGroup' => 200, 'ItemDesc' => 'Melakukan perkelahian di lingkungan sekolah atau d', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:21:37.000', 'Group' => 'Berat', 'Article' => 10],
            ['TransNo' => 430, 'TransGroup' => 200, 'ItemDesc' => 'Menggunakan sepeda motor tanpa helm', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur dan diingatkan dengan lisan oleh Penegak Disiplin Sekolah (PDS) dicatat dalam buku pelanggaran dan ditanda tangani siswa.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:13:48.000', 'Group' => 'Ringan', 'Article' => 6],
            ['TransNo' => 450, 'TransGroup' => 200, 'ItemDesc' => 'Mengucapkan kata-kata kebencian, kasar, atau kotor', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:21:54.000', 'Group' => 'Berat', 'Article' => 11],
            ['TransNo' => 460, 'TransGroup' => 200, 'ItemDesc' => 'Membawa senjata tajam ke sekolah', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:21:46.000', 'Group' => 'Berat', 'Article' => 7],
            ['TransNo' => 480, 'TransGroup' => 200, 'ItemDesc' => 'Membawa, melihat/menonton, atau mengedarkan pornog', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:22:16.000', 'Group' => 'Berat', 'Article' => 12],
            ['TransNo' => 510, 'TransGroup' => 200, 'ItemDesc' => 'Membawa senjata api ke sekolah', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:21:20.000', 'Group' => 'Berat', 'Article' => 8],
            ['TransNo' => 560, 'TransGroup' => 200, 'ItemDesc' => 'Melakukan sikap atau tindakan/perilaku yang menyin', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Arial;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:24:29.000', 'Group' => 'Berat', 'Article' => 21],
            ['TransNo' => 570, 'TransGroup' => 200, 'ItemDesc' => 'Melakukan tindak pidana yang sudah ditangani pihak', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Dikeluarkan dari SMA Plus PGRI Cibinong tanpa ada sanksi atau peringatan sebelumnya.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:27:35.000', 'Group' => 'Luar Biasa', 'Article' => 7],
            ['TransNo' => 600, 'TransGroup' => 200, 'ItemDesc' => 'Terbukti hamil dan atau telah menikah dalam status', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Dikeluarkan dari SMA Plus PGRI Cibinong tanpa ada sanksi atau peringatan sebelumnya.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:27:30.000', 'Group' => 'Luar Biasa', 'Article' => 6],
            ['TransNo' => 630, 'TransGroup' => 200, 'ItemDesc' => 'Terbukti melakukan kekerasan fisik terhadap guru', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Dikeluarkan dari SMA Plus PGRI Cibinong tanpa ada sanksi atau peringatan sebelumnya.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:26:45.000', 'Group' => 'Luar Biasa', 'Article' => 1],
            ['TransNo' => 660, 'TransGroup' => 200, 'ItemDesc' => 'Merokok masih berstatus siswa SMA Plus PGRI Cibino', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:21:08.000', 'Group' => 'Berat', 'Article' => 5],
            ['TransNo' => 680, 'TransGroup' => 200, 'ItemDesc' => 'Berbuat yang tidak menyenangkan bagi warga dan tam', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur tertulis oleh PDS dicatat dalam buku pelanggaran ditanda tangani siswa dan diketahui orang tua.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:17:42.000', 'Group' => 'Sedang', 'Article' => 7],
            ['TransNo' => 690, 'TransGroup' => 200, 'ItemDesc' => 'Keluar kelas saat pembelajaran berlangsung tanpa a', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur tertulis oleh PDS dicatat dalam buku pelanggaran ditanda tangani siswa dan diketahui orang tua.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:17:46.000', 'Group' => 'Sedang', 'Article' => 8],
            ['TransNo' => 720, 'TransGroup' => 100, 'ItemDesc' => 'Memakai switer yang menutupi identitas sekolah', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur tertulis oleh PDS dicatat dalam buku pelanggaran ditanda tangani siswa dan diketahui orang tua.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:17:49.000', 'Group' => 'Sedang', 'Article' => 9],
            ['TransNo' => 730, 'TransGroup' => 100, 'ItemDesc' => 'Mencuri dengan sengaja barang milik sekolah atau b', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:22:19.000', 'Group' => 'Berat', 'Article' => 13],
            ['TransNo' => 740, 'TransGroup' => 100, 'ItemDesc' => 'Tidak masuk sekolah 1 (satu) sampai 3 (tiga) hari', 'Punishment' => '{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur dan diingatkan dengan lisan oleh Penegak Disiplin Sekolah (PDS) dicatat dalam buku pelanggaran dan ditanda tangani siswa.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:11:46.000', 'Group' => 'Ringan', 'Article' => 2],
            ['TransNo' => 750, 'TransGroup' => 100, 'ItemDesc' => 'Memakai perhiasan mahal atau mewah ke sekolah', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur dan diingatkan dengan lisan oleh Penegak Disiplin Sekolah (PDS) dicatat dalam buku pelanggaran dan ditanda tangani siswa.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:14:11.000', 'Group' => 'Ringan', 'Article' => 7],
            ['TransNo' => 770, 'TransGroup' => 100, 'ItemDesc' => 'Tidak ikut upacara bendera hari Senin atau apel so', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur dan diingatkan dengan lisan oleh Penegak Disiplin Sekolah (PDS) dicatat dalam buku pelanggaran dan ditanda tangani siswa.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:12:29.000', 'Group' => 'Ringan', 'Article' => 3],
            ['TransNo' => 780, 'TransGroup' => 100, 'ItemDesc' => 'Tidak memakai seragam ke sekolah', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur tertulis oleh PDS dicatat dalam buku pelanggaran ditanda tangani siswa dan diketahui orang tua.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:15:48.000', 'Group' => 'Sedang', 'Article' => 2],
            ['TransNo' => 790, 'TransGroup' => 100, 'ItemDesc' => 'Mengotori lingkungan sekolah', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur tertulis oleh PDS dicatat dalam buku pelanggaran ditanda tangani siswa dan diketahui orang tua.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:17:35.000', 'Group' => 'Sedang', 'Article' => 6],
            ['TransNo' => 800, 'TransGroup' => 100, 'ItemDesc' => 'Menggunakan motor yang menggunakan knalpot brisik', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Ditegur tertulis oleh PDS dicatat dalam buku pelanggaran ditanda tangani siswa dan diketahui orang tua.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:18:05.000', 'Group' => 'Sedang', 'Article' => 13],
            ['TransNo' => 810, 'TransGroup' => 100, 'ItemDesc' => 'Tidak menghormati dan memuliakan guru', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:20:55.000', 'Group' => 'Berat', 'Article' => 2],
            ['TransNo' => 820, 'TransGroup' => 100, 'ItemDesc' => 'Parkir atau menyimpan kendaraan di luar tempat yan', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:21:04.000', 'Group' => 'Berat', 'Article' => 4],
            ['TransNo' => 830, 'TransGroup' => 100, 'ItemDesc' => 'Mabuk atau minum minuman keras', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:21:12.000', 'Group' => 'Berat', 'Article' => 6],
            ['TransNo' => 840, 'TransGroup' => 100, 'ItemDesc' => 'Melakukan kekerasan, pemukulan, pemalakan, atau an', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:21:24.000', 'Group' => 'Berat', 'Article' => 9],
            ['TransNo' => 850, 'TransGroup' => 100, 'ItemDesc' => 'Berpacaran', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Arial;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:24:11.000', 'Group' => 'Berat', 'Article' => 17],
            ['TransNo' => 860, 'TransGroup' => 100, 'ItemDesc' => 'Berjudi secara langsung maupun melalui media sosia', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Arial;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:24:25.000', 'Group' => 'Berat', 'Article' => 20],
            ['TransNo' => 870, 'TransGroup' => 100, 'ItemDesc' => 'Menyalah gunakan uang sekolah yang dititip oleh or', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Arial;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Orang tua dipanggil ke sekolah, siswa dan orang tua membuat perjanjian di atas kertas bermeterai, berjanji tidak mengulangi lagi pelanggaran, dan bersedia menerima sanksi apapun dari sekolah bila kembali melanggar.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:24:34.000', 'Group' => 'Berat', 'Article' => 22],
            ['TransNo' => 890, 'TransGroup' => 100, 'ItemDesc' => 'Terbukti terlibat dalam kelompok atau geng motor', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Dikeluarkan dari SMA Plus PGRI Cibinong tanpa ada sanksi atau peringatan sebelumnya.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:27:20.000', 'Group' => 'Luar Biasa', 'Article' => 4],
            ['TransNo' => 900, 'TransGroup' => 100, 'ItemDesc' => 'Terbukti melakukan perundungan (bullying)', 'Punishment' => '{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Calibri;}{\f1\fnil Arial monospaced for SAP;}}  {\colortbl ;\red59\green59\blue59;}  {\*\generator Riched20 10.0.19041}\viewkind4\uc1   \pard\cf1\f0\fs16\lang1033 Dikeluarkan dari SMA Plus PGRI Cibinong tanpa ada sanksi atau peringatan sebelumnya.\f1\par  }  ', 'Status' => 'Y', 'UserName' => 'agayanu', 'LastUpdate' => '2026-01-12 10:27:25.000', 'Group' => 'Luar Biasa', 'Article' => 5],
        ]);
    }
}
